# =============================================================================
# Source repositories
# =============================================================================

[".local/src/emacs"]
    type = "git-repo"
    url = "https://github.com/emacs-mirror/emacs.git"
    refreshPeriod = "168h"


[".local/src/emacspeak"]
    type = "git-repo"
    url = "https://github.com/tvraman/emacspeak.git"
    refreshPeriod = "168h"


[".local/src/ble.sh"]
    type = "git-repo"
    url = "https://github.com/akinomyoga/ble.sh.git"
    refreshPeriod = "168h"

[".local/bin/pay-respects"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "iffse/pay-respects" "pay-respects-*.*.*-x86_64-unknown-linux-musl.tar.zst" | quote }}
    executable = true
    path = "pay-respects"
